### ISSUE TITLE
Iter Crash After Phone Objective

### ISSUE THREAD

**Issue by Chaoxufurwa** [braidy08/piracy_pandemonium#1]
Map seems to have a compatibility error with Iter. Crash occurs immediately after interacting with the phone once all 3 movies are downloaded.

[crash.txt](https://github.com/braidy08/piracy_pandemonium/files/14625211/crash.txt)

Abridged version of the log here.

------------------------------------------------------------------------------------------------------------------

Application has crashed: C++ exception
mods/Iter/lua/navigationmanager.lua:579: bad argument #1 to 'ipairs' (table expected, got nil)

SCRIPT STACK

itr_get_coarse_pos_between() @mods/Iter/lua/navigationmanager.lua:579
_execute_coarce_search() @mods/Iter/lua/navigationmanager.lua:953
search_coarse() lib/managers/navigationmanager.lua:2210
objective_func() @mods/Streamlined Heisting/lua/groupaistatebesiege.lua:403
_assign_enemy_groups_to_task() @mods/Streamlined Heisting/lua/groupaistatebesiege.lua:279
_assign_enemy_groups_to_assault() @mods/Streamlined Heisting/lua/groupaistatebesiege.lua:241
original() lib/managers/group_ai_states/groupaistatebesiege.lua:799
_upd_assault_task() @mods/base/req/core/Hooks.lua:264
_upd_police_activity() @mods/Streamlined Heisting/lua/groupaistatebesiege.lua:784
_queue_police_upd_task() @mods/Streamlined Heisting/lua/groupaistatebesiege.lua:794
update() lib/managers/group_ai_states/groupaistatebesiege.lua:102
update() lib/managers/groupaimanager.lua:23
original() lib/setups/gamesetup.lua:808
update() @mods/base/req/core/Hooks.lua:264
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:559

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        

-------------------------------

Current thread: Main

-------------------------------

**Comment by braidy08** [comment]
should be fixed with commit 3bf4adcb10ac2d49d7299c7c331228b331cae987
